"""Preference pairs: candidates, controlled pairs, pairing, drawing sets, ordering."""

from .axes import CONTROLLED_AXES, MAXIMUM_WORD_GAP, ControlledAxis, axes_for
from .build import (
    build_axes,
    build_candidate_mode,
    build_combination,
    load_candidate_settings,
    load_controlled_settings,
    load_judging_settings,
    load_pair_set_settings,
)
from .candidates import (
    BANDS,
    CANDIDATE_MODES,
    Candidate,
    CandidateMode,
    band_bounds,
    band_for,
    directives,
)
from .ordering import (
    ORDER_COMBINATIONS,
    ORDERS,
    OrderCombination,
    Ordered,
    Outcome,
    order_by_construction,
    order_by_judge,
    read_answer,
    side_shown_first,
    summarise,
    winner_of,
)
from .pool import (
    MAXIMUM_PER_MOMENT,
    MINIMUM_DISTANCE,
    DrawPlan,
    Offered,
    Pairing,
    distance_between,
    draw,
    hold_out_by_lecture,
    pairs_of_moment,
    take,
)

__all__ = [
    "BANDS",
    "CANDIDATE_MODES",
    "CONTROLLED_AXES",
    "MAXIMUM_PER_MOMENT",
    "MAXIMUM_WORD_GAP",
    "MINIMUM_DISTANCE",
    "ORDERS",
    "ORDER_COMBINATIONS",
    "Candidate",
    "CandidateMode",
    "ControlledAxis",
    "DrawPlan",
    "Offered",
    "OrderCombination",
    "Ordered",
    "Outcome",
    "Pairing",
    "axes_for",
    "band_bounds",
    "band_for",
    "build_axes",
    "build_candidate_mode",
    "build_combination",
    "directives",
    "distance_between",
    "draw",
    "hold_out_by_lecture",
    "load_candidate_settings",
    "load_controlled_settings",
    "load_judging_settings",
    "load_pair_set_settings",
    "order_by_construction",
    "order_by_judge",
    "pairs_of_moment",
    "read_answer",
    "side_shown_first",
    "summarise",
    "take",
    "winner_of",
]
